import 'package:almighty/models/contact_model.dart';
import 'package:almighty/models/items_model.dart';
import 'package:almighty/models/order_model.dart';
List<Items> cartItems;
Order order;
final String AUTH_KEY = "authKey";
final String CONTACT_KEY = "contactModel";
final String PHONE = "phone";
final String PASSWORD = "password";
Contact contact;
String otp;
String phone;